name: tidy and format

on: [pull_request,push]
jobs:
  c-linter:
    name: c-linter
    runs-on: ubuntu-latest
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: build chatroom
        uses: actions/checkout@master
      - name: clangd init  
        run:  apt-get update && apt-get -qq -y install curl clang-tidy cmake jq clang cppcheck clang-format && chmod +x ./.github/c-linter.sh && chmod +x ./.github/format.sh
        shell: bash
      - name: c-linter
        run: ./.github/c-linter.sh
        shell: bash
      - name: format
        run: ./.github/format.sh
        