name: tidy

on:
  pull_request:
    branches: [ chatroom , dev]
    
jobs:
  build_make:
    runs-on: ubuntu-latest
    steps:

      - name: clang-tidy check
        uses: muxee/clang-tidy-action@0.0.1-rc1